#!/usr/bin/env bash

# Keybinding wrapper for cleaning unused plugins

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN_DIR="$CURRENT_DIR/../bin"

# Run the clean command
"$BIN_DIR/clean"

