#!/usr/bin/env bash

# Keybinding wrapper for installing plugins

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN_DIR="$CURRENT_DIR/../bin"

# Run the install command
"$BIN_DIR/install"

