#!/usr/bin/env bash

# Keybinding wrapper for updating plugins

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN_DIR="$CURRENT_DIR/../bin"

# Run the update command
"$BIN_DIR/update"

