name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup environment
        run: |
          echo "Testing on bash version: $BASH_VERSION"
          which bash
          bash --version
      
      - name: Run test suite
        run: ./run_tests.sh
      
      - name: Test summary
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ All tests passed"
          else
            echo "❌ Some tests failed"
            exit 1
          fi

  shellcheck:
    name: ShellCheck Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          ignore_paths: tests/bats

